version: "3.8"

x-base: &base
  build:
    dockerfile: ./docker_dev/Dockerfile
    context: .
services:
  web:
    <<: *base
    restart: always
    volumes:
      - .:/app
    command: npm run serve
    ports:
      - "8080:8080"
#     json-server
      - "3000:3000"
  ui:
    <<: *base
    restart: always
    volumes:
      - .:/app
    command: vue ui --host 0.0.0.0
    ports:
      - "8000:8000"
